# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /chocolate_house

# Copy the current directory contents into the container at /chocolate_house
COPY . /chocolate_house

# Install necessary dependencies
RUN pip install -r requirements.txt

# Run app.py when the container launches
CMD ["python", "app.py"]
